### ISSUE TITLE
refreshing  min/max. I can't commit anymore? 

### ISSUE THREAD

**Issue by d-kz** [Brennan-M/TwitterFeels#6]
on line 129 add the following:
max = 0
min = 0

**Comment by Brennan-M** [comment]
Can you go to settings for the repository?

**Comment by d-kz** [comment]
I can fork it, but HackCU closed it, thus I can't commit to original one. You could probably just extend access on this one.

**Comment by ianks** [comment]
You will probably have to change your 'origin'

```
$ git remote remove origin
$ git remote add origin https://github.com/Brennan-M/TwitterFeels
```

**Comment by Brennan-M** [comment]
I added u as a collabotator. You're good to go now

**Comment by d-kz** [comment]
:shipit: 
Done! Thanks, Ian!
